FROM alpine

RUN wget https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip
RUN unzip terraform_1.6.6_linux_amd64.zip && rm terraform_1.6.6_linux_amd64.zip
RUN mv terraform /usr/bin/terraform

WORKDIR terraform

COPY _infrastructure/terraform .

ENV AWS_PROFILE=ostop-prod

CMD rm -rf .terraform/ && rm -f .terraform.lock.hcl && terraform init --backend-config=envs/prod/terraform.cfg && terraform apply --var-file=envs/prod/vars -auto-approve
